OuicarBundle\Entity\Car:
    type: entity
    table: null
    repositoryClass: OuicarBundle\Repository\CarRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        mileage:
            type: integer
        priceDay1:
            type: integer
            column: price_day_1
        priceDay3:
            type: integer
            column: price_day_3
        priceDay7:
            type: integer
            column: price_day_7
    lifecycleCallbacks: {  }
